name: Dpkg Source
description: Build a debian source package

inputs:
  source_options:
    description: Additional options for dpkg-source
    required: false
  genchanges_options:
    description: Additional options for dpkg-genchanges
    required: false

runs:
  using: docker
  image: docker://ghcr.io/fragoi/debuild:u24.0
  entrypoint: source.sh
  env:
    SOURCE_OPTS: ${{ inputs.source_options }}
    GENCHANGES_OPTS: ${{ inputs.genchanges_options }}
